### PR TITLE
Showcase. Mobile experience.

### PR DESCRIPTION
**Pull request by Alena1508**
Add styles to Helm for search field and patient's information area

### CODE REVIEW

**Comment by tony-shannon** [comment]
Please add a screenshot to explain what styles have been added

Waiting for @simongamester to review this set , thanks

**Comment by simongamester** [comment]
Hi @Alena1508

Please could you provide more information on this issue?

Thanks,

Simon

**Comment by Alena1508** [comment]
Before it was like this https://prnt.sc/l7vvi4
I added styles for mobile resolution and now it looks this way http://prntscr.com/l9ioqu

These changes were made for Showcase theme, but Helm theme also has those elements so I added them here too. 
@tony-shannon @simongamester

**Comment by tony-shannon** [comment]
thanks Alena, what issue was this for?

**Comment by tony-shannon** [comment]
ok thanks @Alena1508 
@simongamester can you review this one also please

**Comment by Alena1508** [comment]
This is related for task - https://github.com/PulseTile/PulseTile-React-Core/issues/267
@tony-shannon

**Pull request merged**
